apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: game-2048
spec:
  template:
    spec:
      containers:
        # Replace with your docker registry info
        - image: registry.digitalocean.com/tekton-ci/2048-game:latest
          ports:
            - containerPort: 80
